<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAumjA3Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAumjA3Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAumjA3Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAumjA3Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAumjA3Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'AumjA3Y',
    'container.build_id' => '96ecd2c0',
    'container.build_time' => 1607552744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAumjA3Y');
